import 'package:floor/floor.dart';
import 'package:colombo_rocco/database/TypeConverters/datetimeconverter.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Activity {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()
  final int id;

  final DateTime day;
  final int steps;

  //Default constructor
  Activity(this.id, this.day, this.steps);
}//Activity