import 'package:floor/floor.dart';


//Here, we are saying to floor that this is a class that defines an entity
@entity
class Activity {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()
  final DateTime day;

  final double calories;

  //Default constructor
  Activity(this.day, this.calories);
}//Activity