import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Sleep {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()
  final DateTime day;

  final int deep;
  final int light;
  final int rem;
  final int wake;

  //Default constructor
  Sleep(this.day, this.deep, this.light, this.rem, this.wake);
}//Sleep